# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "031fa933df09c87c5497fc87787e643b"
name = "swoo-print-app"
handle = "swoo-print-app"
application_url = "https://aluminum-immigrants-margaret-evidence.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "swooapp.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products"

[auth]
redirect_urls = [
  "https://aluminum-immigrants-margaret-evidence.trycloudflare.com/auth/callback",
  "https://aluminum-immigrants-margaret-evidence.trycloudflare.com/auth/shopify/callback",
  "https://aluminum-immigrants-margaret-evidence.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
